# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2018

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Archives: /archives
  About: /about

archive_generator:
    per_page: 0
    yearly: false
    monthly: false
    daily: false  

# ===========================================
# Widget Settings
# ===========================================
# widget function
# false: disable
# widget_custom: custom your widget
#   title: your widget title
#   content: Add your html code in here. Example: <p>testing...</p>
widget:
  Tags: true
  Categories: false
  Custom: true

widget_custom:
    title: Slogan
    content: <p>Because we can</p>

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  fancybox: false

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics:
# Google Analytics
google_analytics:

# Duoshuo
duoshuo_shortname:
# Disqus
disqus_shortname:

# Gitment
# Introduction: https://imsun.net/posts/gitment-introduction/
gitment:
    enable: false                                             # gitment评论系统开关
    owner: gd4Ark                                        # GitHub用户名
    repo: gd4Ark.github.io                               # 存储评论数据的GitHub仓库的仓库名
    client_id: ca4ae20760cf27ad5c6c                          # OAuth Application的Client ID
    client_secret: 671788fb8d6aed08906b70340a8ba3088ec03f39  # OAuth Application的Client Secret
    lazy: false                                               # 评论懒加载开关

# Gitalk
# Introduction: https://github.com/gitalk/gitalk
gitalk:
    enable : true
    owner: gd4Ark                                        # GitHub用户名
    repo: gd4Ark.github.io                               # 存储评论数据的GitHub仓库的仓库名
    client_id: ca4ae20760cf27ad5c6c                          # OAuth Application的Client ID
    client_secret: 671788fb8d6aed08906b70340a8ba3088ec03f39  # OAuth Application的Client Secret
    admin: ['gd4Ark']
    distractionFreeMode: false
# ===========================================
# Version
# ===========================================
version: 1.1
